server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # SPA routing — todas las rutas van a index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # En producción, /api lo enruta Traefik directamente al container de la API
  # En desarrollo, Vite lo proxea en su propio server
}
